site_name: async-pipelines

theme:
    name: 'material'

repo_name: alexkeating/async-pipelines
repo_url: https://github.com/alexkeating/async-pipelines 
edit_uri: ""

nav:
    - Home: index.md
    - Api: api.md

markdown_extensions:
    - admonition
    - codehilite
    - mkautodoc


extra_css:
    - css/custom.css
