#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="pipelines tests"

set -x

${PREFIX}black --check $SOURCE_FILES
${PREFIX}flake8 $SOURCE_FILES
${PREFIX}mypy -p pipelines
# Add isort stuff
