#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="pipelines tests"

set -x

${PREFIX}autoflake --in-place --recursive $SOURCE_FILES
${PREFIX}seed-isort-config --application-directories=pipelines
${PREFIX}isort --project=pipelines --recursive --apply $SOURCE_FILES
${PREFIX}black $SOURCE_FILES
